version: "3.8"

services:
  tgwebapp:
    image: ghcr.io/korjavin/arithproblems:bb34fdba5f580b0423726a7cb3f0545317b2da9c
    container_name: arithproblems
    networks:
      - vaultwarden_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arithproblems.rule=Host(`${DNS_NAME}`)"
      - "traefik.http.routers.arithproblems.entrypoints=websecure"
      - "traefik.http.routers.arithproblems.tls.certresolver=myresolver"

    restart: unless-stopped

networks:
  vaultwarden_default:
    external: true
