version: "3.8"

services:
  tgwebapp:
    image: ghcr.io/korjavin/arithproblems:15d970075731b619229537b2f5b80abd3e8bb6ae
    container_name: arithproblems
    networks:
      - vaultwarden_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arithproblems.rule=Host(`${DNS_NAME}`)"
      - "traefik.http.routers.arithproblems.entrypoints=websecure"
      - "traefik.http.routers.arithproblems.tls.certresolver=myresolver"

    restart: unless-stopped

networks:
  vaultwarden_default:
    external: true
