version: "3.8"

services:
  tgwebapp:
    image: ghcr.io/korjavin/arithproblems:202ba1ca0edb6671871624fbc6cf5b9933fba0c4
    container_name: arithproblems
    networks:
      - vaultwarden_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arithproblems.rule=Host(`${DNS_NAME}`)"
      - "traefik.http.routers.arithproblems.entrypoints=websecure"
      - "traefik.http.routers.arithproblems.tls.certresolver=myresolver"

    restart: unless-stopped

networks:
  vaultwarden_default:
    external: true
