name: Deploy Math Worksheet Generator

on:
  push:
    branches:
      - master # Or your default branch, e.g., main
  workflow_dispatch:

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write # Required to push to GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Optional: List files to confirm structure before cd (useful for debugging)
      # - name: List files in workspace root before cd
      #   run: ls -laR

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          # Context will default to the working-directory
          # Dockerfile path will default to Dockerfile in the working-directory
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          # Alternative tagging strategy:
          # tags: |
          #   ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          #   ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
          #   ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:v1.0.${{ github.run_number }}

      - name: Image Digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
      
      - name: 📝 Update and commit docker-compose.yml
        # This step checks out the repo, updates the image tag, and pushes the change to deploy branch.
        run: |
          # Configure Git with a user name and email.
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # Create and switch to deploy branch (or switch if it exists)
          git checkout -B deploy
          
          sed -i "s|image: ghcr.io/korjavin/arithproblems:.*|image: ghcr.io/korjavin/arithproblems:${{ github.sha }}|g" docker-compose.yml
          
          # Add the changed file, commit it, and push it to the 'deploy' branch.
          git add docker-compose.yml
          git commit -m "ci: Update image tag to ${{ github.sha }}"
          git push origin deploy --force

      - name: 🚀 Trigger Portainer Redeploy Webhook
        # This step runs AFTER the image is pushed and the git commit is done.
        # It guarantees the image exists before Portainer tries to pull.
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.PORTAINER_REDEPLOY_HOOK }}
          webhook_secret: "trigger"
